import { useCallback, useMemo, useState } from "react";
import {
  ReactFlow,
  ReactFlowProvider,
  Background,
  BackgroundVariant,
  Controls,
  MiniMap,
  Panel,
  useNodesState,
  useEdgesState,
  addEdge,
  Connection,
  Edge,
  Node,
  MarkerType,
  useReactFlow,
} from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import ChatCardNode, { CardMessage, ChatCardData } from "@/components/chat/ChatCardNode";
import { Plus, Sparkles, Trash2, LayoutGrid } from "lucide-react";

const nodeTypes = { chatCard: ChatCardNode };

// --- Demo AI logic ---
const RESPONSES: { match: RegExp; reply: string }[] = [
  {
    match: /jwt/i,
    reply: `A **JWT** is \`header.payload.signature\`. The payload is base64-encoded — not encrypted.
\`\`\`js
import jwt from "jsonwebtoken";
const token = jwt.sign({ sub: "user_1" }, process.env.SECRET, { expiresIn: "1h" });
\`\`\`
Always verify the signature server-side.`,
  },
  {
    match: /random/i,
    reply: `**Randomness** refers to the lack of pattern or predictability in events.

In computing, random numbers are usually generated by *pseudorandom number generators* (PRNGs) — deterministic but appearing random.

\`\`\`js
// Random integer between 1 and 100
const n = Math.floor(Math.random() * 100) + 1;
console.log(n);
\`\`\`

True randomness can come from physical phenomena like atmospheric noise.`,
  },
  {
    match: /sql|duplicate/i,
    reply: `Find duplicates with \`GROUP BY\`:
\`\`\`sql
SELECT email, COUNT(*) AS n
FROM users
GROUP BY email
HAVING COUNT(*) > 1;
\`\`\``,
  },
  {
    match: /cors/i,
    reply: `**CORS** errors happen when your server doesn't whitelist the request origin.
\`\`\`js
app.use(cors({ origin: ["http://localhost:3000"], credentials: true }));
\`\`\``,
  },
  {
    match: /regex|email/i,
    reply: `Practical email regex:
\`\`\`js
const re = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;
\`\`\``,
  },
];

function generateReply(prompt: string): string {
  for (const r of RESPONSES) if (r.match.test(prompt)) return r.reply;
  return `Here's a thought on **"${prompt.slice(0, 60)}${prompt.length > 60 ? "…" : ""}"**:

This canvas is a workspace for parallel conversations. Drag cards around, resize them, connect them, or branch a reply into a new card.

\`\`\`ts
// Try asking about: jwt, sql, cors, random, regex
function explore(idea: string) {
  return idea.split("").reverse().join("");
}
\`\`\``;
}

// ----------------------

const initialNodes: Node[] = [
  {
    id: "welcome",
    type: "chatCard",
    dragHandle: ".card-drag-handle",
    position: { x: 80, y: 80 },
    data: { title: "Welcome", messages: [] },
    style: { width: 380, height: 360 },
  },
];

const CanvasInner = () => {
  const [nodes, setNodes, onNodesChange] = useNodesState<Node>(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState<Edge>([]);
  const { screenToFlowPosition, fitView } = useReactFlow();
  const [counter, setCounter] = useState(2);

  const updateCard = useCallback(
    (id: string, updater: (d: ChatCardData) => Partial<ChatCardData>) => {
      setNodes((nds) =>
        nds.map((n) => (n.id === id ? { ...n, data: { ...n.data, ...updater(n.data as ChatCardData) } } : n))
      );
    },
    [setNodes]
  );

  const handleSend = useCallback(
    (cardId: string, content: string) => {
      const userMsg: CardMessage = { id: crypto.randomUUID(), role: "user", content };
      updateCard(cardId, (d) => ({
        messages: [...d.messages, userMsg],
        isLoading: true,
      }));
      const delay = 600 + Math.random() * 800;
      setTimeout(() => {
        const aiMsg: CardMessage = { id: crypto.randomUUID(), role: "assistant", content: generateReply(content) };
        updateCard(cardId, (d) => ({
          messages: [...d.messages, aiMsg],
          isLoading: false,
          title:
            d.title === "Welcome" || d.title === "New Chat"
              ? content.slice(0, 30) + (content.length > 30 ? "…" : "")
              : d.title,
        }));
      }, delay);
    },
    [updateCard]
  );

  const handleDelete = useCallback(
    (id: string) => {
      setNodes((nds) => nds.filter((n) => n.id !== id));
      setEdges((eds) => eds.filter((e) => e.source !== id && e.target !== id));
    },
    [setNodes, setEdges]
  );

  const handleRename = useCallback(
    (id: string, title: string) => updateCard(id, () => ({ title })),
    [updateCard]
  );

  const handleBranch = useCallback(
    (sourceId: string, fromMessageId: string) => {
      const source = nodes.find((n) => n.id === sourceId);
      if (!source) return;
      const sd = source.data as ChatCardData;
      const idx = sd.messages.findIndex((m) => m.id === fromMessageId);
      const inherited = idx >= 0 ? sd.messages.slice(0, idx + 1) : [];
      const newId = `card-${counter}`;
      setCounter((c) => c + 1);
      const newNode: Node = {
        id: newId,
        type: "chatCard",
        dragHandle: ".card-drag-handle",
        position: {
          x: (source.position?.x ?? 0) + (source.width ?? 380) + 80,
          y: (source.position?.y ?? 0) + 40,
        },
        data: { title: "Branch", messages: inherited, parentId: sourceId },
        style: { width: 380, height: 360 },
      };
      setNodes((nds) => [...nds, newNode]);
      setEdges((eds) => [
        ...eds,
        {
          id: `e-${sourceId}-${newId}`,
          source: sourceId,
          target: newId,
          animated: true,
          style: { stroke: "hsl(var(--primary))", strokeWidth: 1.5 },
          markerEnd: { type: MarkerType.ArrowClosed, color: "hsl(var(--primary))" },
        },
      ]);
    },
    [nodes, setNodes, setEdges, counter]
  );

  const createCardAt = useCallback(
    (flowX: number, flowY: number) => {
      const newId = `card-${counter}`;
      setCounter((c) => c + 1);
      const newNode: Node = {
        id: newId,
        type: "chatCard",
        dragHandle: ".card-drag-handle",
        position: { x: flowX - 190, y: flowY - 180 },
        data: { title: "New Chat", messages: [] },
        style: { width: 380, height: 360 },
      };
      setNodes((nds) => [...nds, newNode]);
      return newId;
    },
    [counter, setNodes]
  );

  const addCard = useCallback(() => {
    const center = screenToFlowPosition({
      x: window.innerWidth / 2,
      y: window.innerHeight / 2,
    });
    createCardAt(center.x, center.y);
  }, [screenToFlowPosition, createCardAt]);

  const onPaneDoubleClick = useCallback(
    (event: React.MouseEvent) => {
      const pos = screenToFlowPosition({ x: event.clientX, y: event.clientY });
      createCardAt(pos.x, pos.y);
    },
    [screenToFlowPosition, createCardAt]
  );

  // Create a new connected child card with selected text as quoted context
  const handleCreateFromSelection = useCallback(
    (sourceId: string, selectedText: string, prompt: string) => {
      const source = nodes.find((n) => n.id === sourceId);
      if (!source) return;
      const newId = `card-${counter}`;
      setCounter((c) => c + 1);

      const quoted = selectedText.length > 280 ? selectedText.slice(0, 280) + "…" : selectedText;
      const userContent = `> ${quoted.replace(/\n/g, "\n> ")}\n\n${prompt}`;
      const userMsg: CardMessage = {
        id: crypto.randomUUID(),
        role: "user",
        content: userContent,
      };

      const titleSeed = prompt.slice(0, 30) + (prompt.length > 30 ? "…" : "");
      const newNode: Node = {
        id: newId,
        type: "chatCard",
        dragHandle: ".card-drag-handle",
        position: {
          x: (source.position?.x ?? 0) + (source.width ?? 380) + 80,
          y: (source.position?.y ?? 0) + 40,
        },
        data: {
          title: titleSeed || "From selection",
          messages: [userMsg],
          parentId: sourceId,
          isLoading: true,
        },
        style: { width: 380, height: 360 },
      };

      setNodes((nds) => [...nds, newNode]);
      setEdges((eds) => [
        ...eds,
        {
          id: `e-${sourceId}-${newId}`,
          source: sourceId,
          target: newId,
          animated: true,
          style: { stroke: "hsl(var(--primary))", strokeWidth: 1.5 },
          markerEnd: { type: MarkerType.ArrowClosed, color: "hsl(var(--primary))" },
        },
      ]);

      // Generate AI reply about the selection + prompt
      const delay = 600 + Math.random() * 800;
      setTimeout(() => {
        const aiMsg: CardMessage = {
          id: crypto.randomUUID(),
          role: "assistant",
          content: generateReply(`${selectedText}\n${prompt}`),
        };
        setNodes((nds) =>
          nds.map((n) =>
            n.id === newId
              ? {
                  ...n,
                  data: {
                    ...n.data,
                    messages: [...((n.data as ChatCardData).messages || []), aiMsg],
                    isLoading: false,
                  },
                }
              : n
          )
        );
      }, delay);
    },
    [nodes, setNodes, setEdges, counter]
  );

  // Pan/zoom to a parent card
  const handleNavigateParent = useCallback(
    (parentId: string) => {
      const parent = nodes.find((n) => n.id === parentId);
      if (!parent) return;
      const cx = (parent.position?.x ?? 0) + (parent.width ?? 380) / 2;
      const cy = (parent.position?.y ?? 0) + (parent.height ?? 360) / 2;
      setCenter(cx, cy, { zoom: 1, duration: 500 });
      setNodes((nds) =>
        nds.map((n) => ({ ...n, selected: n.id === parentId }))
      );
    },
    [nodes, setNodes]
  );


  const clearAll = useCallback(() => {
    if (!confirm("Clear all chat cards from the canvas?")) return;
    setNodes([]);
    setEdges([]);
  }, [setNodes, setEdges]);

  const onConnect = useCallback(
    (c: Connection) =>
      setEdges((eds) =>
        addEdge(
          {
            ...c,
            animated: true,
            style: { stroke: "hsl(var(--primary))", strokeWidth: 1.5 },
            markerEnd: { type: MarkerType.ArrowClosed, color: "hsl(var(--primary))" },
          },
          eds
        )
      ),
    [setEdges]
  );

  // Inject handlers into node data
  const enrichedNodes = useMemo(
    () =>
      nodes.map((n) => ({
        ...n,
        data: {
          ...n.data,
          onSend: handleSend,
          onDelete: handleDelete,
          onRename: handleRename,
          onBranch: handleBranch,
        },
      })),
    [nodes, handleSend, handleDelete, handleRename, handleBranch]
  );

  return (
    <div className="w-full h-full bg-background relative">
      <ReactFlow
        nodes={enrichedNodes}
        edges={edges}
        onNodesChange={onNodesChange}
        onEdgesChange={onEdgesChange}
        onConnect={onConnect}
        onPaneClick={onPaneClick}
        nodeTypes={nodeTypes}
        fitView
        minZoom={0.2}
        maxZoom={2}
        proOptions={{ hideAttribution: true }}
        defaultEdgeOptions={{
          style: { stroke: "hsl(var(--primary))", strokeWidth: 1.5 },
        }}
      >
        <Background
          variant={BackgroundVariant.Dots}
          gap={24}
          size={1.5}
          color="hsl(var(--muted-foreground) / 0.25)"
        />
        <Controls
          className="!bg-card/80 !backdrop-blur-xl !border !border-border/60 !rounded-lg !shadow-xl [&_button]:!bg-transparent [&_button]:!border-border/40 [&_button]:!text-foreground [&_button:hover]:!bg-muted"
          showInteractive={false}
        />
        <MiniMap
          className="!bg-card/80 !backdrop-blur-xl !border !border-border/60 !rounded-lg !shadow-xl"
          nodeColor="hsl(var(--primary) / 0.6)"
          maskColor="hsl(var(--background) / 0.7)"
          pannable
          zoomable
        />

        {/* Top toolbar */}
        <Panel position="top-left" className="!m-3">
          <div className="flex items-center gap-2 px-3 py-2 rounded-xl bg-card/80 backdrop-blur-xl border border-border/60 shadow-xl">
            <div className="flex items-center gap-2 pr-2 border-r border-border/60">
              <div className="w-7 h-7 rounded-lg bg-primary/15 border border-primary/30 flex items-center justify-center">
                <Sparkles className="w-3.5 h-3.5 text-primary" />
              </div>
              <div>
                <h2 className="text-xs font-semibold text-foreground leading-tight">XenCoder Canvas</h2>
                <p className="text-[10px] text-muted-foreground leading-tight">
                  {nodes.length} card{nodes.length === 1 ? "" : "s"}
                </p>
              </div>
            </div>
            <button
              onClick={addCard}
              className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-md bg-primary text-primary-foreground text-xs font-medium hover:bg-primary/90 transition-all"
            >
              <Plus className="w-3.5 h-3.5" />
              New Chat
            </button>
            <button
              onClick={() => fitView({ duration: 400, padding: 0.2 })}
              className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-md bg-muted/60 text-foreground text-xs font-medium hover:bg-muted border border-border/60 transition-all"
            >
              <LayoutGrid className="w-3.5 h-3.5" />
              Fit
            </button>
            <button
              onClick={clearAll}
              className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-md bg-muted/60 text-muted-foreground text-xs font-medium hover:bg-destructive/10 hover:text-destructive border border-border/60 transition-all"
            >
              <Trash2 className="w-3.5 h-3.5" />
              Clear
            </button>
          </div>
        </Panel>

        {/* Empty state */}
        {nodes.length === 0 && (
          <Panel position="top-center" className="!top-1/3">
            <div className="flex flex-col items-center text-center gap-3 px-6 py-8 rounded-2xl bg-card/80 backdrop-blur-xl border border-border/60 shadow-2xl max-w-sm">
              <div className="w-14 h-14 rounded-2xl bg-primary/10 border border-primary/20 flex items-center justify-center">
                <Sparkles className="w-7 h-7 text-primary" />
              </div>
              <h3 className="text-base font-bold text-foreground">Your canvas is empty</h3>
              <p className="text-xs text-muted-foreground">
                Spin up parallel chats, resize them, branch replies, and connect ideas on an infinite canvas.
              </p>
              <button
                onClick={addCard}
                className="flex items-center gap-1.5 px-4 py-2 rounded-md bg-primary text-primary-foreground text-xs font-medium hover:bg-primary/90 transition-all"
              >
                <Plus className="w-3.5 h-3.5" />
                Create your first chat
              </button>
            </div>
          </Panel>
        )}
      </ReactFlow>

      <style>{`
        .react-flow__attribution { display: none !important; }
        .react-flow__handle { transition: all 0.15s; }
        .react-flow__handle:hover { transform: scale(1.4); }
      `}</style>
    </div>
  );
};

const ChatPage = () => {
  // Break out of DashboardLayout's p-8 padding and fill the available space
  return (
    <div className="-m-8 h-[calc(100vh)] bg-background">
      <ReactFlowProvider>
        <CanvasInner />
      </ReactFlowProvider>
    </div>
  );
};

export default ChatPage;
